### ISSUE TITLE
Support R8 full mode

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-video-android#979]
**Describe the bug**
App crashes when running a release build. I've encountered this issue in my app, and upon checking, the same problem occurs in the demo app as well.

**SDK version**
- 0.4.3
- develop branch (latest)

**To Reproduce**
1. In demo-app, change the build variant to `developmentRelease` or `productionRelease`. (`developmentNonMinifiedRelease` is fine)
2. Build and run
3. App crashes

**Expected behavior**
App should run normally without crashing.

**Device:**
 - Vendor and model: Samsung Galaxy S20
 - Android version: 13

**Comment by aleksandar-apostolov** [comment]
Hi @workspace,
Thanks for your report.
In the demo app there was an issue with some models being wiped by proguard.
We've updated `develop` today with this [#PR (980)](https://github.com/GetStream/stream-video-android/pull/980)

This is the exception we fixed:
`
Fatal Exception: kotlin.reflect.jvm.internal.KotlinReflectionInternalError: This callable does not support a default call: public constructor StreamRemoteConfig(...)
 `
 
 Thanks for updating this issue with further information if this does not solve the problem. It would be of great help to us if you could also include some logs.

**Comment by workspace** [comment]
Hi @aleksandar-apostolov 

Thank you for the quick fix.

I wanted to attach a log, but it was difficult to provide a clear reference as the logs occurring in my app and the demo app are different. 

I have not yet been able to receive 0.4.4-SNAPSHOT, but I will check if the Snapshot has solved the problem and get back to you.

**Comment by aleksandar-apostolov** [comment]
Hey @workspace 
The configuration in question is in the `demo-app` not in the SDK, no update to the SDK was made. We found no other crash on the `release` variant.
It might be that there is also an issue in the SDK, but at the moment we are note able to reproduce this. You can provide both logs if that is possible it might give us an insight as to what is crashing the application.

**Comment by workspace** [comment]
I was still experiencing issues, so I compared the stream-video-android project with my project and identified the exact cause.

The cause is R8.

From AGP 8.0, R8 operates in full mode by default. According to [this commit ](https://github.com/GetStream/stream-video-android/commit/2428043c9e783d9c5f60fc5f976ea92745431500#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19R40) in the stream-video-android project, R8 full mode was temporarily disabled during the update of the AGP version. If R8 full mode is enabled, the demo app crashes immediately upon launch, just like my project.

Since AGP 8.0 adopts R8 full mode as the default, it's likely that customers using this library will face the same issue. I've somewhat resolved this issue by applying two modifications:

- Adding Retrofit related rule to the core ProGuard rule.
- Using IntentCompat in the Intent.streamCallId extension.

However, I haven't conducted a comprehensive review of all the libraries used by stream-video-android, so could you assist in reviewing them? I have submitted my changes as a PR #982 for suggestion.

**Comment by aleksandar-apostolov** [comment]
I will update the issue and labels.

**Comment by skydoves** [comment]
#982 has been merged 🎉 This fix will be contained in the next stable release. Thank you for your contribution, @workspace!
